### ISSUE TITLE
Typewriter mode does not work after switching to different file, console error "addClasses is not a function"

### ISSUE THREAD

**Issue by batrand** [davisriedel/obsidian-typewriter-mode#52]
Hey there, I've tried to reproduce this on a new vault, tried disabling all the plugins etc but could not get it to happen in other vaults, but in this vault, typewriter mode doesn't work. 

On first load, typewriter mode works, but once you switch to another file, this error throws in console, and typewriter mode stops working:

```
app.js:1 TypeError: r.addClasses is not a function
    at f.loadPerWindowProps (plugin:typewriter-mode:1:5656)
    at f.onReconfigured (plugin:typewriter-mode:1:5392)
    at f.onLoad (plugin:typewriter-mode:1:5237)
    at new f (plugin:typewriter-mode:1:1876)
    at new eval (plugin:typewriter-mode:1:5066)
    at e.create (app.js:1:361676)
    at e.update (app.js:1:362106)
    at e.setState (app.js:1:462573)
    at t.set (app.js:1:1358863)
    at t.set (app.js:1:2068898)
    at t.setViewData (app.js:1:2083288)
    at t.setData (app.js:1:1757849)
    at t.<anonymous> (app.js:1:1757752)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

This throws every time you switch to a different file.

I've tried everything I could think of to identify if there was a plugin that caused the conflict, but had no luck! I copied out the .obsidian folder to a new vault, and can confirm that the problem exists there as well. I've attached a copy, hopefully you can help me identify what the problem is?

Steps:
- Open the vault and console.
- Use the arrow key to scroll up and down; observe that the cursor stays centered.
- Switch to the other file. Observe in console the error is logged. Use arrow key to scroll: cursor no longer stays centered, typewriter mode stops working.

[reproduce.zip](https://github.com/davisriedel/obsidian-typewriter-mode/files/14209459/reproduce.zip)

**Comment by franrodalg** [comment]
It seems to be happening to me as well. I thought it was only when I launched a template, but I now realise it also happens when I just switch to a different note.

```
app.js:1 TypeError: r.addClasses is not a function
    at f.loadPerWindowProps (plugin:typewriter-mode:1:5656)
    at f.onReconfigured (plugin:typewriter-mode:1:5392)
    at f.onLoad (plugin:typewriter-mode:1:5237)
    at new f (plugin:typewriter-mode:1:1876)
    at new eval (plugin:typewriter-mode:1:5066)
    at e.create (app.js:1:361676)
    at e.update (app.js:1:362106)
    at e.setState (app.js:1:462573)
    at t.set (app.js:1:1358863)
    at t.set (app.js:1:2068898)
```

**Comment by davisriedel** [comment]
This seems to be an issue due to interference of another plugin. In fact when I installed `Writing Goals` in one of my personal vaults, I got the same issue. I opened the vault @batrand provided, and it also contained the `Writing Goals` plugin. But disabling it did not resolve the issue in this vault. So I suppose there must be another plugin interfering. I will have to do some investigation to find out, what functionality/behavior of those plugins causes the issue in typewriter mode.

**Comment by franrodalg** [comment]
I do not have Writing Goals installed, though. Shall I provide a list of my
installed plugins?

**Comment by davisriedel** [comment]
I found the issue: I am watching for iframes to make this work with canvas (since each canvas node is an iframe). This caused an issue with all plugins that add an iframe to the markdown editor. I was able to fix this, and released a new version as a quick fix.

**Comment by franrodalg** [comment]
Many thanks @davisriedel! Looking forward to giving it a try :)

**Comment by franrodalg** [comment]
I can confirm it seems to be working as expected after the update. Thanks @davisriedel!

**Comment by batrand** [comment]
thanks for the update! confirm fixed as well :)
